// Font Color Changer
function fccdSetup() {
	document.querySelector(".fccd-btn").addEventListener("click", function() {
		let color = document.querySelector(".fccd-i").value;
		let colorNames = [
			"AliceBlue",
		    "AntiqueWhite",
		    "Aqua",
		    "Aquamarine",
		    "Azure",
		    "Beige",
		    "Bisque",
		    "Black",
		    "BlanchedAlmond",
		    "Blue",
		    "BlueViolet",
		    "Brown",
		    "BurlyWood",
		    "CadetBlue",
		    "Chartreuse",
		    "Chocolate",
		    "Coral",
		    "CornflowerBlue",
		    "Cornsilk",
		    "Crimson",
		    "Cyan",
		    "DarkBlue",
		    "DarkCyan",
		    "DarkGoldenRod",
		    "DarkGray",
		    "DarkGreen",
		    "DarkKhaki",
		    "DarkMagenta",
		    "DarkOliveGreen",
		    "DarkOrange",
		    "DarkOrchid",
		    "DarkRed",
		    "DarkSalmon",
		    "DarkSeaGreen",
		    "DarkSlateBlue",
		    "DarkSlateGray",
		    "DarkTurquoise",
		    "DarkViolet",
		    "DeepPink",
		    "DeepSkyBlue",
		    "DimGray",
		    "DodgerBlue",
		    "FireBrick",
		    "FloralWhite",
		    "ForestGreen",
		    "Fuchsia",
		    "Gainsboro",
		    "GhostWhite",
		    "Gold",
		    "GoldenRod",
		    "Gray",
		    "Green",
		    "GreenYellow",
		    "HoneyDew",
		    "HotPink",
		    "IndianRed",
		    "Indigo",
		    "Ivory",
		    "Khaki",
		    "Lavender",
		    "LavaenderBlush",
		    "LawnGreen",
		    "LemonChiffon",
		    "LightBlue",
		    "LightCoral",
		    "LightCyan",
		    "LightGoldenRodYellow",
		    "LightGray",
		    "LightGreen",
		    "LightPink",
		    "LightSalmon",
		    "LightSeaGreen",
		    "LightSkyBlue",
		    "LightSlateGray",
		    "LightSteelBlue",
		    "LightYellow",
		    "Lime",
		    "LimeGreen",
		    "Linen",
		    "Magenta",
		    "Maroon",
		    "MediumAquaMarine",
		    "MediumBlue",
		    "MediumOrchid",
		    "MediumPurple",
		    "MediumSeaGreen",
		    "MediumSlateBlue",
		    "MediumSpringGreen",
		    "MediumTurquosie",
		    "MediumVoiletRed",
		    "MidnightBlue",
		    "MintCream",
		    "MistyRose",
		    "Moccasin",
		    "NavajoWhite",
		    "Navy",
		    "OldLace",
		    "Olive",
		    "OliveDrab",
		    "Orange",
		    "OrangeRed",
		    "Orchid",
		    "PaleGoldenRod",
		    "PaleGreen",
		    "PaleTurquoise",
		    "PaleVoiletRed",
		    "PapayaWhip",
		    "PeachPuff",
		    "Peru",
		    "Pink",
		    "Plum",
		    "PowderBlue",
		    "Purple",
		    "RebeccaPurple",
		    "Red",
		    "RosyBrown",
		    "RoyalBlue",
		    "SaddleBrown",
		    "Salmon",
		    "SandyBrown",
		    "SeaGreen",
		    "SeaShell",
		    "Sienna",
		    "Silver",
		    "SkyBlue",
		    "SlateBlue",
		    "SlateGray",
		    "Snow",
		    "SpringGreen",
		    "SteelBlue",
		    "Tan",
		    "Teal",
		    "Thistle",
		    "Tomato",
		    "Turquoise",
		    "Voilet",
		    "Wheat",
		    "White",
		    "WhiteSmoke",
		    "Yellow",
		    "YellowGreen"
	    ];
	    let validateHex = /^#[0-9A-F]{6}$/i;

	    let isValidColor = false;

	    colorNames.forEach(function(v) {
	    	if (color.toLowerCase().includes(v.toLowerCase())) isValidColor = true;
	    });

	    if (validateHex.test(color) === true && isValidColor === false || isValidColor === true) {
	    	document.querySelector(".fccd").style = `color: ${color}`;
	    } else {
	    	alert("Invalid color. If you're using HEX please include the #\nFor a list of HTML Color Names please see here: https://www.w3schools.com/tags/ref_colornames.asp");
	    }
	});
}

if (document.readyState !== 'loading') {
	setTimeout(fccdSetup, 0);
} else {
	document.addEventListener('DOMContentLoaded', function () {
		setTimeout(fccdSetup, 0);
	});
}